### ISSUE TITLE
Allow configuration using pyproject.toml

### ISSUE THREAD

**Issue by pradyunsg** [pyinvoke/invoke#537]
As per [PEP 518](https://www.python.org/dev/peps/pep-0518/#specification), tools can use `tool.<pypi-name>` namespace within the `pyproject.toml` file if they own `<pypi-name>` on PyPI.

Allowing configuration via the above mechanism would allow for users to have a single file in their root directory, for configuring this tool (and others) as for their project.

**Comment by pradyunsg** [comment]
Making this the preferred way for configuration would help prevent/workaround issues like #498.

**Comment by pradyunsg** [comment]
unrelated: the GitHub wiki for this project is empty; consider removing it?

**Comment by bitprophet** [comment]
I like the sound of this but haven't looked into it yet. I suspect it would also dovetail nicely with adding TOML support for our own config files.

**Comment by pradyunsg** [comment]
Also, ties in cleanly with #471.

**Comment by pradyunsg** [comment]
FWIW, here's how the default configuration could look in TOML:

```toml
[tool.invoke.tasks]
dedupe = true
auto_dash_names = true
collection_name = "tasks"
search_root = "."  # there's no null/None in TOML

[tool.invoke.run]
echo = false
# lots of stuff; I think you got the idea.
```

TOML's next release will have dotted keys, so once that's the version available everywhere, this could all just be replaced with:

```ini
[tool.invoke]
tasks.dedupe = true
...
run.echo = false
...
```
