### ISSUE TITLE
Print of many carriage returns is broken under specifics conditions

### ISSUE THREAD

**Issue by fabien-michel** [pyinvoke/invoke#816]
There is a strange behavior when the command output many carriage return to print content on same lines.
A "???" character is printed, and content jump to a new line.
This occurred for me with invoke running a docker compose command on a terminal width of 319 cols.

Step to reproduce :
Set terminal to have 319 cols (`tput cols` return 319)
Have docker-compose installed

demo file docker-compose.yml
```yaml
version: '3'

services:
  echo:
    image: k8s.gcr.io/echoserver:1.10
    ports:
          - "8080:8080"
  echo1:
    image: k8s.gcr.io/echoserver:1.10
    ports:
          - "8081:8080"
  echo2:
    image: k8s.gcr.io/echoserver:1.10
    ports:
          - "8082:8080"
  echo3:
    image: k8s.gcr.io/echoserver:1.10
    ports:
          - "8083:8080"
```

invoke tasks.py
```python
from invoke import task

@task
def docker_compose_up(ctx):
    ctx.run('docker compose up', pty=True)
```

Startup is fine:
```inv docker-compose-up```

Press Ctrl+C to stop containers

You should see output like this:
![2021-09-29_100030](https://user-images.githubusercontent.com/1167556/135230952-3b9136c8-3537-4515-b0f8-905e5fefc273.png)

and many many lines printed.

The expected output is to have only fours lines printed, and refreshed.

319 cols is a fullscreen terminal for me.

OS: Arch linux
Terminal: alacritty (on wayland)
Invoke: 1.6.0
Python: 3.9.7
